name: Build on Windows
on: push

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Nim
        run: |
          cd ${HOME}
          C:\msys64\usr\bin\wget.exe https://nim-lang.org/download/nim-2.0.2_x64.zip
          7z.exe x nim-2.0.2_x64.zip -y
          cd nim-2.0.2
          finish.exe
      - name: Install build deps
        run: choco install yasm innosetup rcedit zip reshack
      - name: Install scons
        run: python -m pip install scons
      - name: Update path
        run: echo "${HOME}/.nimble/bin;${HOME}/nim-2.0.2/bin;C:\msys64\mingw64\bin;C:\Program Files (x86)\Resource Hacker" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Install nimble deps
        run: nimble setup -y
      - name: Save SHAs of submodules
        run: 'git submodule status > .submodules.tmp'
      - name: Prep dist config
        run: cp dist_config.example.json dist_config.json

      - name: prereq cache
        id: prereq-cache
        uses: actions/cache@v3
        with:
          path: |
            vendor/godot/bin
            fonts
          key: ${{ runner.os }}-prereq-cache-v3-${{ hashFiles('.submodules.tmp') }}
      - name: build prereqs
        run: nimble dist_prereqs
        if: steps.prereq-cache.outputs.cache-hit != 'true'
      - name: Download and copy mesa
        # github runner doesn't have a GPU, so we need to link to mesa
        # to start godot
        run: |
          md -f vendor/godot/bin
          md mesa
          cd mesa
          C:\msys64\usr\bin\wget.exe https://github.com/pal1000/mesa-dist-win/releases/download/19.2.5/mesa3d-19.2.5-release-mingw.7z
          7z.exe e mesa3d-19.2.5-release-mingw.7z -y -o"..\vendor\godot\bin" x64/opengl32.dll
          cd ..
          rm mesa -Recurse
        if: steps.prereq-cache.outputs.cache-hit != 'true'

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Dist
        run: nimble dist_package
      - uses: actions/upload-artifact@v3
        with:
          name: Enu Windows Distribution
          path: |
            dist/*.exe
            dist/*.zip
